#!/bin/bash

export JASMINE_SERVER_UNIT=0
export JASMINE_CLIENT_UNIT=0
export JASMINE_CLIENT_INTEGRATION=0
export LONG_RUNNING_CHILD_PROCESS_LOG_LEVEL=debug
export VELOCITY_DEBUG=1
export VELOCITY_DEBUG_MIRROR=1

meteor --test --port 4444
